"use client";
import { useState } from "react";
import { CheckCircle2, LockKeyhole } from "lucide-react";
import { attitudeHistory, attitudeItems } from "@/lib/sa3-demo-data";
import { Sa3LineChart } from "@/components/sa3-chart";

export function AttitudeSelfAssessment(){
 const [saved,setSaved]=useState(false);
 return <div className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600"><LockKeyhole className="mr-2 inline" size={17}/>Tu autoevaluación es personal. Puedes consultar tu evolución, pero no comparar tu actitud con otros alumnos.</div><div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="card p-6"><h2 className="text-lg font-extrabold">Autoevaluación configurable</h2><p className="mt-1 text-sm text-slate-500">Estos ítems son ejemplos editables por el profesorado.</p><div className="mt-6 space-y-5">{attitudeItems.filter(i=>i.active).map(item=><AttitudeField key={item.id} label={item.label} type={item.type}/>)}</div><label className="mt-5 block text-xs font-bold uppercase tracking-wide text-slate-500">¿Cómo valorarías tu actitud durante esta situación de aprendizaje?<textarea rows={4} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label><label className="mt-5 block text-xs font-bold uppercase tracking-wide text-slate-500">¿Qué aspecto de tu actitud podrías mejorar?<textarea rows={4} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label><button onClick={()=>setSaved(true)} className="mt-5 rounded-xl bg-[#1e6b4f] px-4 py-2.5 text-sm font-bold text-white">Guardar autoevaluación</button>{saved&&<p className="mt-4 text-sm font-semibold text-[#1e6b4f]"><CheckCircle2 className="mr-2 inline" size={17}/>Registro guardado en modo demo.</p>}</section><aside className="card p-6"><h2 className="font-extrabold">Mi evolución</h2><p className="mt-1 text-sm text-slate-500">Índice personal orientativo generado a partir de tus propios registros.</p><Sa3LineChart data={attitudeHistory.map(h=>({label:h.periodLabel,value:h.scoreIndex??0}))}/></aside></div></div>
}
function AttitudeField({label,type}:{label:string;type:"scale_1_5"|"yes_no"|"text"}){if(type==="text")return <label className="block text-xs font-bold uppercase tracking-wide text-slate-500">{label}<input className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label>;if(type==="yes_no")return <label className="block text-xs font-bold uppercase tracking-wide text-slate-500">{label}<select className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option>Sí</option><option>No</option></select></label>;return <label className="block text-xs font-bold uppercase tracking-wide text-slate-500">{label}<input type="range" min="1" max="5" defaultValue="4" className="mt-2 w-full"/></label>}
