"use client";
import { useMemo,useState } from "react";
import { BookOpen, ClipboardList, Library, MessageSquareMore, PencilRuler, Plus, SmilePlus, Users } from "lucide-react";
import { students } from "@/lib/demo-data";
import { alternativeGames, attitudeItems, designedSessions, gameRatings, groupGameRatingSummary, sa3TheoryContents } from "@/lib/sa3-demo-data";
import { Sa3BarChart } from "@/components/sa3-chart";

type Tab="overview"|"sessions"|"ratings"|"attitude"|"games"|"content";

export function TeacherSa3Dashboard(){
 const [group,setGroup]=useState("1º Bach A"); const groupStudents=useMemo(()=>students.filter(s=>s.group===group),[group]); const [studentId,setStudentId]=useState(groupStudents[0]?.id??""); const [tab,setTab]=useState<Tab>("overview");
 const selected=students.find(s=>s.id===studentId)??groupStudents[0];
 const changeGroup=(g:string)=>{setGroup(g);setStudentId(students.find(s=>s.group===g)?.id??"")};
 return <div className="space-y-6"><section className="card grid gap-4 p-5 md:grid-cols-2"><Select label="Grupo" value={group} onChange={changeGroup}><option>1º Bach A</option><option>1º Bach B</option></Select><Select label="Alumno/a" value={selected?.id??""} onChange={setStudentId}>{groupStudents.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={ClipboardList} label="Sesiones creadas" value="18" note="Borradores + entregas"/><Kpi icon={PencilRuler} label="Entregadas" value="12" note="67% del grupo"/><Kpi icon={Users} label="Participación" value="79%" note="Actividad registrada"/><Kpi icon={MessageSquareMore} label="Valoración media" value="4.1/5" note="Resumen anónimo"/><Kpi icon={BookOpen} label="Contenidos" value={String(sa3TheoryContents.length)} note="Publicados demo"/></section>
 <div className="flex gap-2 overflow-x-auto pb-1">{([["overview","Resumen"],["sessions","Sesiones"],["ratings","Valoraciones"],["attitude","Autoevaluaciones"],["games","Crear juego"],["content","Publicar material"]] as [Tab,string][]).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold ${tab===k?"bg-slate-950 text-white":"border border-slate-200 bg-white text-slate-600"}`}>{l}</button>)}</div>
 {tab==="overview"&&<div className="grid gap-5 xl:grid-cols-2"><section className="card p-6"><h2 className="text-lg font-extrabold">Valoración agregada de juegos</h2><p className="mt-1 text-sm text-slate-500">Resultados generales sin nombres individuales.</p><Sa3BarChart data={groupGameRatingSummary}/></section><section className="card p-6"><h2 className="text-lg font-extrabold">Juegos mejor valorados</h2><p className="mt-1 text-sm text-slate-500">Orden agregado por valoración media; no clasifica alumnado.</p><div className="mt-5 space-y-3">{alternativeGames.slice(0,3).map((g,i)=><div key={g.id} className="flex justify-between rounded-xl bg-slate-50 p-4 text-sm"><strong>{g.name}</strong><span>{[4.6,4.4,4.1][i]}/5</span></div>)}</div><h3 className="mt-6 font-extrabold">Comentarios recientes</h3><div className="mt-3 space-y-2">{gameRatings.map(r=><p key={r.id} className="rounded-xl border border-slate-100 p-3 text-sm text-slate-600">“{r.comment}”</p>)}</div></section></div>}
 {tab==="sessions"&&<section className="card overflow-hidden"><div className="border-b border-slate-200 p-6"><h2 className="font-extrabold">Sesiones · {selected?.name}</h2><p className="text-sm text-slate-500">Consulta, estado de entrega y feedback docente.</p></div>{designedSessions.map(s=><article key={s.id} className="border-b border-slate-100 p-6 last:border-0"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-bold">{s.title}</h3><p className="mt-1 text-xs text-slate-400">{s.updatedAt} · {s.status==="draft"?"Borrador":"Entregada"}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{s.status}</span></div><label className="mt-4 block text-xs font-bold uppercase tracking-wide text-slate-500">Feedback<textarea defaultValue={s.teacherFeedback??""} rows={2} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Añadir comentario para el alumno/a"/></label><button className="mt-3 rounded-xl bg-[#1e6b4f] px-3 py-2 text-sm font-bold text-white">Guardar feedback</button></article>)}</section>}
 {tab==="ratings"&&<section className="card p-6"><h2 className="font-extrabold">Resultados grupales de valoración</h2><p className="mt-1 text-sm text-slate-500">La vista general se mantiene anonimizada. Los comentarios individuales solo deben consultarse cuando exista una finalidad docente.</p><Sa3BarChart data={groupGameRatingSummary}/></section>}
 {tab==="attitude"&&<div className="grid gap-5 xl:grid-cols-2"><section className="card p-6"><SmilePlus className="text-[#1e6b4f]"/><h2 className="mt-4 font-extrabold">Autoevaluación · {selected?.name}</h2><p className="mt-2 text-sm text-slate-500">Consulta individual privada. No se generan comparaciones entre alumnos.</p><div className="mt-4 grid gap-2">{attitudeItems.map(i=><div key={i.id} className="rounded-xl bg-slate-50 p-3 text-sm font-semibold">{i.label} · {i.type.replaceAll("_"," ")}</div>)}</div></section><AttitudeConfig/></div>}
 {tab==="games"&&<GameForm/>}{tab==="content"&&<ContentForm/>}</div>
}
function GameForm(){return <section className="card p-6"><div className="flex items-center gap-3"><Library className="text-[#1e6b4f]"/><div><h2 className="font-extrabold">Crear ficha de juego</h2><p className="text-sm text-slate-500">El catálogo puede ampliarse sin modificar código.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Nombre"/><Field label="Participantes recomendados"/><Field label="Espacio"/><Field label="Duración aproximada" type="number"/><Field label="Categorías"/><label className="text-xs font-bold text-slate-500">INTENSIDAD<select className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option>Baja</option><option>Media</option><option>Alta</option></select></label>{["Descripción","Objetivo","Materiales","Reglas","Variantes","Recomendaciones de seguridad"].map(l=><label key={l} className="md:col-span-2 text-xs font-bold text-slate-500">{l.toUpperCase()}<textarea rows={2} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label>)}</div><div className="mt-4 flex gap-2"><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">Añadir imagen</button><button className="rounded-xl bg-[#1e6b4f] px-4 py-2.5 text-sm font-bold text-white">Guardar ficha</button></div></section>}
function ContentForm(){return <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="card p-6"><div className="flex items-center gap-3"><BookOpen className="text-[#1e6b4f]"/><div><h2 className="font-extrabold">Publicar material SA3</h2><p className="text-sm text-slate-500">Documentos, explicaciones, infografías, enlaces, vídeos o fichas.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Título"/><Field label="Categoría"/><label className="text-xs font-bold text-slate-500">TIPO<select className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option>Documento</option><option>Explicación</option><option>Infografía</option><option>Enlace</option><option>Vídeo enlazado</option><option>Ficha de juego</option></select></label><Field label="Enlace"/><label className="md:col-span-2 text-xs font-bold text-slate-500">EXPLICACIÓN<textarea rows={5} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label></div><button className="mt-5 rounded-xl bg-[#1e6b4f] px-4 py-2.5 text-sm font-bold text-white">Publicar</button></section><section className="card p-6"><h2 className="font-extrabold">Material publicado</h2><p className="mt-1 text-sm text-slate-500">Resumen de documentos y contenidos disponibles en SA3.</p><div className="mt-4 divide-y divide-slate-100">{sa3TheoryContents.map(item=><div key={item.id} className="py-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.category} · {item.type.replace("_"," ")}</p></div><span className="rounded-full bg-[#e7f2ed] px-2.5 py-1 text-[11px] font-bold text-[#164c3a]">Publicado</span></div></div>)}</div></section></div>}
function AttitudeConfig(){return <section className="card p-6"><div className="flex items-center gap-3"><Plus className="text-[#1e6b4f]"/><div><h2 className="font-extrabold">Configurar ítems</h2><p className="text-sm text-slate-500">Los ejemplos actuales son editables.</p></div></div><div className="mt-5 space-y-3"><Field label="Texto del ítem"/><label className="block text-xs font-bold text-slate-500">TIPO<select className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option>Escala 1-5</option><option>Sí / No</option><option>Texto</option></select></label><button className="rounded-xl bg-[#1e6b4f] px-4 py-2.5 text-sm font-bold text-white">Añadir ítem</button></div></section>}
function Kpi({icon:Icon,label,value,note}:{icon:typeof Users;label:string;value:string;note:string}){return <article className="card p-5"><div className="flex justify-between"><p className="text-sm text-slate-500">{label}</p><Icon size={18} className="text-[#1e6b4f]"/></div><p className="mt-3 text-3xl font-extrabold">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></article>}
function Select({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm font-semibold">{children}</select></label>}
function Field({label,type="text"}:{label:string;type?:string}){return <label className="text-xs font-bold text-slate-500">{label.toUpperCase()}<input type={type} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label>}
