import type { SecondYearQuizQuestion, SecondYearTheorySection } from "@/lib/second-year-theory-topics";

// Síntesis propia de los documentos aportados. Páginas del archivo PDF, empezando por 1.
export const capacitySources = [
  "Alfonso Jiménez Gutiérrez (coord.). Entrenamiento Personal. Bases, fundamentos y aplicaciones. PDF pp. 38–42, 61–69, 75–76, 93–95, 111, 143–151.",
  "Carlos Gillone. Entrenamiento combinado de fuerza y resistencia. PDF pp. 14–24, 34, 50–52.",
  "Darío Cappa. Entrenamiento de la potencia muscular. PDF pp. 10–13.",
  "Francisco Tarantino. Entrenamiento propioceptivo. PDF pp. 14–16 y 21–22.",
  "Jerónimo Milo. Manual de fuerza: anatomía y entrenamiento 2. PDF pp. 74–76.",
  "Óscar Morán Esquerdo. Enciclopedia de ejercicios de musculación. PDF pp. 14–15 y 270.",
  "Correr, saltar, lanzar. Fundamentos de la carrera. PDF pp. 5–7.",
  "Periodización del entrenamiento deportivo. Organización del libro y planificación de la fuerza. PDF p. 5.",
];

export const basicCapacities = [
  { name: "Fuerza", types: "Máxima · explosiva / rápida · fuerza resistencia", system: "Sistema nervioso + fibras musculares + tendones", adaptation: "Reclutamiento y coordinación; capacidad muscular de producir tensión", sport: "Rebote en baloncesto: producir fuerza en poco tiempo", color: "bg-emerald-50 border-emerald-200" },
  { name: "Resistencia", types: "Aeróbica · anaeróbica aláctica y láctica", system: "ATP-PCr + glucólisis + metabolismo oxidativo", adaptation: "Transporte y utilización de oxígeno; sostener y repetir el esfuerzo", sport: "Fútbol: recuperar entre aceleraciones durante el partido", color: "bg-sky-50 border-sky-200" },
  { name: "Velocidad", types: "Reacción · gestual · desplazamiento", system: "Percepción y respuesta nerviosa + fuerza rápida + ATP-PCr", adaptation: "Responder, coordinar y aplicar fuerza con rapidez", sport: "Bádminton: reaccionar y llegar al volante", color: "bg-amber-50 border-amber-200" },
  { name: "Flexibilidad / movilidad", types: "Activa / pasiva · estática / dinámica", system: "Articulaciones + complejo musculotendinoso + control nervioso", adaptation: "Amplitud utilizable y control del movimiento", sport: "Paso de valla: amplitud de cadera sin perder estabilidad", color: "bg-violet-50 border-violet-200" },
];

export function capacitySections(sa: 1 | 2): SecondYearTheorySection[] {
  return [
    { title: sa === 1 ? "Cuatro capacidades para interpretar mis pruebas" : "Del resultado al estímulo: entrenar una capacidad concreta", paragraphs: [
      "Fuerza, resistencia, velocidad y flexibilidad son capacidades relacionadas, pero una prueba no mide todas a la vez. Un salto horizontal informa sobre fuerza explosiva de las piernas; no equivale a medir fuerza máxima. Las flexiones o los abdominales repetidos se relacionan con fuerza resistencia. Cooper y Course Navette orientan sobre resistencia; los sprints sobre velocidad; las pruebas de alcance sobre movilidad de regiones concretas.",
      sa === 1 ? "Relaciona cada marca con el protocolo, tu técnica y tus condiciones ese día. El 5 × 10 m incorpora cambios de dirección: además de velocidad exige frenar, orientar el cuerpo y volver a acelerar. Elige uno o dos objetivos a partir de tus datos, sin convertir un resultado en una etiqueta personal." : "Selecciona la manifestación que necesitas: saltar más alto, repetir esfuerzos o mantener un gesto con control requieren estímulos distintos. La carga depende del ejercicio, volumen, intensidad, descanso y frecuencia; completar muchas repeticiones no garantiza entrenar potencia.",
      "Base: Morán, PDF p. 14; Cappa, PDF pp. 10–13; Correr, saltar, lanzar, PDF pp. 5–7. La asociación con los test de clase es una aplicación didáctica.",
    ] },
    { title: "Fuerza: músculo, sistema nervioso y tipos de contracción", paragraphs: [
      "La fuerza es la capacidad de producir tensión. La orden nerviosa activa unidades motoras: una motoneurona y las fibras que inerva. Dentro de las fibras, actina y miosina interactúan en los sarcómeros utilizando ATP, con la intervención del calcio. Ganar fuerza depende tanto de la coordinación y activación nerviosa como de las adaptaciones del músculo; no se reduce a tener más volumen muscular.",
      "Fuerza máxima: mayor fuerza que puede producirse en unas condiciones determinadas. Fuerza explosiva o rápida: aplicar mucha fuerza en poco tiempo, como en una batida o lanzamiento. Fuerza resistencia: sostener o repetir contracciones frente a la fatiga. Son manifestaciones relacionadas; fuerza explosiva y potencia no son términos idénticos: la potencia relaciona fuerza y velocidad de movimiento.",
      "Contracción concéntrica: el músculo activo se acorta mientras vence la resistencia; los extensores de rodilla y cadera elevan el cuerpo al subir de una sentadilla. Excéntrica: el músculo produce tensión mientras se alarga; esos extensores controlan la bajada o amortiguan una recepción. Isométrica: produce tensión sin cambio apreciable de longitud ni movimiento articular; por ejemplo, mantener una posición estable. Una misma tarea combina fases y músculos con funciones diferentes.",
      "En el ciclo de estiramiento-acortamiento, una fase excéntrica precede a una concéntrica rápida. En un salto con contramovimiento, el descenso prepara la impulsión mediante mecanismos musculotendinosos y nerviosos. No basta con bajar y subir de cualquier forma: importa la coordinación, la transición y la recepción.",
      sa === 1 ? "Para analizar tu salto, distingue impulso concéntrico, preparación excéntrica y estabilización. Para interpretar las flexiones, observa si el tronco se mantiene estable y si se repite el mismo recorrido. La comparación solo es útil con un protocolo constante." : "Para fuerza general, prioriza técnica y una resistencia que puedas controlar. Para potencia, usa pocas acciones de calidad con intención rápida y descanso suficiente; termina la serie cuando pierdas velocidad o coordinación. Para fuerza resistencia, aumenta gradualmente el trabajo repetido sin deteriorar la ejecución. La isometría sirve para sostener y estabilizar; no sustituye por sí sola todos los recorridos del gesto deportivo.",
      "Asociación rápida: baloncesto, impulso para el rebote = fuerza rápida; aterrizaje = control excéntrico; mantener la posición defensiva = componente isométrico; repetir acciones durante el juego = fuerza resistencia. Son ejemplos de aplicación, no compartimentos aislados.",
      "Base: Jiménez, PDF pp. 38–42 y 93–95; Gillone, PDF pp. 14–22 y 50–52; Cappa, PDF pp. 10–13; Tarantino, PDF p. 21.",
    ] },
    { title: "Resistencia: de dónde sale la energía y qué mejora", paragraphs: [
      "El ATP es la fuente inmediata que utiliza la contracción muscular. Sus reservas son pequeñas y deben reponerse. Los sistemas energéticos trabajan conjuntamente: cambia su contribución según intensidad, duración y pausas; no se encienden uno después de otro como interruptores.",
      "La vía de los fosfágenos (ATP-PCr), llamada anaeróbica aláctica, aporta energía con gran rapidez en acciones muy breves. La glucólisis proporciona ATP a partir de carbohidratos y participa de forma importante al prolongar esfuerzos intensos; se relaciona con la denominación anaeróbica láctica. El metabolismo oxidativo utiliza oxígeno en las mitocondrias y tiene especial importancia para sostener esfuerzos prolongados y recuperar entre acciones.",
      "La resistencia aeróbica depende del transporte de oxígeno por los sistemas respiratorio y cardiovascular y de su utilización muscular. El entrenamiento puede mejorar la capilarización, la capacidad oxidativa y la economía del gesto. Las fibras tipo I poseen un perfil más resistente a la fatiga; las tipo II permiten acciones rápidas y de elevada tensión, con diferencias internas. Ningún deporte utiliza exclusivamente un tipo de fibra.",
      sa === 1 ? "En Cooper o Navette no basta con mirar la distancia o el último periodo: considera el ritmo inicial, la regularidad, la técnica y la fatiga. Un objetivo útil puede combinar mantener más tiempo un ritmo controlado y repetir la prueba con el mismo procedimiento en diciembre." : "El trabajo continuo mantiene una actividad sin pausas; el fraccionado organiza bloques con recuperación. Ajusta primero la duración que puedes sostener con control y después la intensidad o el número de bloques. Acortar el descanso cambia el estímulo: una serie de sprints con pausas insuficientes deja de ser un trabajo de velocidad de máxima calidad.",
      "Asociación rápida: carrera continua en atletismo = gran participación oxidativa; aceleración para un balón dividido = alta demanda inmediata de fosfágenos; repetición de esfuerzos intensos = contribución combinada. En fútbol, la base aeróbica ayuda a sostener el partido y a recuperar entre acciones rápidas.",
      "Base: Gillone, PDF pp. 22–24 y 34; Jiménez, PDF pp. 61–69 y 75–76. Las situaciones deportivas son ejemplos didácticos de estas relaciones.",
    ] },
    { title: "Velocidad: reaccionar, ejecutar y desplazarse", paragraphs: [
      "La velocidad de reacción se refiere a responder a una señal; la gestual, a realizar rápidamente una acción; la de desplazamiento, a recorrer una distancia. En las carreras se distinguen salida, aceleración, velocidad máxima y mantenimiento. El resultado combina percepción, decisión, coordinación y capacidad de aplicar fuerza en poco tiempo.",
      "El sistema nervioso organiza la respuesta y la activación muscular. La coordinación entre músculos, la fuerza rápida y la técnica determinan cuánto de esa respuesta se transforma en movimiento útil. Las acciones muy breves requieren una reposición rápida de ATP, con gran participación del sistema de fosfágenos. Entrenar velocidad no consiste solamente en agotar energía.",
      sa === 1 ? "En nuestro sprint de 30 m con salida lanzada se mide el tramo tras la aceleración previa; el de 60 m desde posición estática sí incluye la salida y la aceleración. Para comparar septiembre y diciembre, conserva distancia, señal, superficie y forma de cronometraje. Un pequeño cambio puede deberse al procedimiento; acompaña la cifra con observaciones técnicas." : "Practica salidas a señales diferentes, recorridos cortos y recuperación suficiente para repetir con calidad. Coloca este trabajo tras el calentamiento y antes de una fatiga importante. Aumentar la distancia no siempre mejora la reacción; entrenar una salida no sustituye toda la velocidad de desplazamiento.",
      "Asociación rápida: bádminton, reconocer la salida del volante = reacción; acelerar la raqueta = velocidad gestual; llegar al fondo de pista = desplazamiento. Fútbol, reaccionar al pase y recorrer 10 m exige además orientación y aceleración.",
      "Base: Correr, saltar, lanzar, PDF pp. 5–7; Cappa, PDF pp. 10–13; Gillone, PDF pp. 22–24.",
    ] },
    { title: "Flexibilidad y movilidad: amplitud con control", paragraphs: [
      "La flexibilidad se relaciona con la amplitud disponible en una articulación o conjunto de articulaciones. En esta unidad llamamos movilidad a utilizar esa amplitud con control. Distinguimos acciones activas, producidas por la propia musculatura, y pasivas, asistidas por una fuerza externa; estáticas, manteniendo una posición, y dinámicas, recorriendo una amplitud. Son dos criterios que pueden combinarse.",
      "La amplitud depende de las características articulares, del complejo musculotendinoso y del control nervioso. Los husos musculares informan sobre longitud y cambios de estiramiento; los órganos tendinosos de Golgi aportan información sobre tensión. La propiocepción permite regular posición, tensión y estabilidad. Su función es más amplia que ganar flexibilidad.",
      "Aunque la musculatura necesita ATP para actuar, esta capacidad no se mejora principalmente agotando una vía energética. Importan el control, la progresión de la amplitud y la respuesta a la tensión. Evita forzar un rango que no puedes controlar. Las técnicas postisométricas alternan contracción y relajación y requieren aprender correctamente su ejecución.",
      sa === 1 ? "El sit and reach, la movilidad de hombro y la inclinación lateral describen zonas y movimientos diferentes. Una buena marca en una prueba no garantiza movilidad en todas las articulaciones. Relaciona la limitación observada con el gesto que quieres mejorar." : "Diferencia preparar un gesto con movilidad dinámica de mantener una posición de estiramiento. Progresa primero en control y después en amplitud, sin rebotes forzados. En una tarea activa, el objetivo es llegar y volver con estabilidad; una ayuda externa no debe sustituir el control propio.",
      "Asociación rápida: paso de valla = movilidad dinámica de cadera; sostener una posición gimnástica = amplitud y control activo; un alcance asistido = componente pasivo. En una recepción de salto, la propiocepción ayuda a ajustar tobillo, rodilla y cadera.",
      "Base: Tarantino, PDF pp. 14–16 y 21–22; Jiménez, PDF p. 151. Las categorías y ejemplos se presentan como organización didáctica del movimiento, no como una receta única de estiramiento.",
    ] },
    { title: sa === 1 ? "Uno o dos objetivos y un plan que cabe en la semana" : "Cómo elegir carga y comprobar la adaptación", paragraphs: [
      "Formula un objetivo principal y, si lo necesitas, un segundo objetivo complementario. En cada uno escribe qué mejorarás, tu punto de partida, cómo lo medirás y cuándo lo revisarás. Ejemplo: mantener una carrera continua controlada durante más tiempo y comprobar la evolución en diciembre; como segundo objetivo, mejorar el control de la recepción del salto mediante una lista de observación.",
      "La dosis incluye ejercicio concreto, series o tiempo, repeticiones o distancia, intensidad y recuperación. Anota también el día de práctica. La escala de esfuerzo de 0 a 10 ayuda a expresar cómo has vivido el trabajo: 0 representa ausencia de esfuerzo y 10 esfuerzo máximo. Hay que aprender a utilizarla; el número no sustituye la observación técnica.",
      "Las clases duran 55 minutos y se distribuyen de lunes a jueves. Como propuesta de aula, reserva aproximadamente 10 minutos para preparación, 35 para tareas y organización y 10 para vuelta a la calma y registro. Alterna las demandas de días consecutivos, consulta la agenda y adapta la semana cuando haya un festivo. No recuperes automáticamente una clase perdida duplicando la carga siguiente.",
      "Progresa una variable cada vez cuando la ejecución sea estable y la recuperación adecuada. Registra qué hiciste y cómo respondió tu cuerpo; después compara con tu indicador. Las dosis del selector son puntos de partida didácticos ajustables por el profesor, no una transcripción de programas para deportistas avanzados.",
      "Base: Jiménez, PDF pp. 94–95 y 111; Cappa, PDF pp. 10–13; Periodización del entrenamiento deportivo, PDF p. 5. El horario y la distribución de minutos corresponden a la adaptación escolar de este proyecto.",
    ] },
  ];
}

export const capacityQuiz: SecondYearQuizQuestion[] = [
  { question: "Al bajar de forma controlada en una sentadilla, los extensores de rodilla realizan principalmente una acción…", options: ["Concéntrica", "Excéntrica", "Sin tensión muscular"], correct: 1, feedback: "Producen tensión mientras se alargan para controlar el descenso." },
  { question: "Para mejorar la fuerza explosiva del salto, conviene priorizar…", options: ["Muchas repeticiones hasta perder técnica", "Solo mantener posiciones estáticas", "Acciones rápidas de calidad y recuperación suficiente"], correct: 2, feedback: "La fuerza rápida exige aplicar fuerza en poco tiempo y conservar la calidad del gesto." },
  { question: "Durante un partido, los sistemas energéticos…", options: ["Contribuyen conjuntamente en proporciones variables", "Funcionan uno solo cada vez", "No participan durante las pausas"], correct: 0, feedback: "La intensidad, duración y recuperación modifican su contribución; la recuperación también requiere energía." },
  { question: "¿Qué ayuda especialmente a sostener esfuerzos aeróbicos?", options: ["Solo aumentar el tamaño de los brazos", "Transportar y utilizar mejor el oxígeno", "Eliminar todas las pausas de cualquier tarea"], correct: 1, feedback: "Intervienen el sistema cardiovascular, los capilares y la capacidad oxidativa muscular." },
  { question: "Responder a una señal y después correr 10 m combina…", options: ["Únicamente flexibilidad pasiva", "Solo fuerza máxima", "Velocidad de reacción y desplazamiento"], correct: 2, feedback: "La respuesta a la señal y el recorrido son componentes distintos de la tarea." },
  { question: "La movilidad articular depende especialmente de…", options: ["Estructuras articulares, músculos, tendones y control nervioso", "Agotar siempre los fosfágenos", "Una sola marca que describe todo el cuerpo"], correct: 0, feedback: "La movilidad es específica del movimiento y requiere amplitud y control." },
  { question: "Si hay un festivo y pierdes una sesión, tu plan debería…", options: ["Duplicar sin más la intensidad al día siguiente", "Reorganizarse según la agenda y la recuperación", "Eliminar el objetivo de diciembre"], correct: 1, feedback: "Planificar también implica adaptar la carga al tiempo disponible y a la respuesta individual." },
];
