import { type SecondYearTheorySection, type SecondYearSportCase } from "@/lib/second-year-theory-topics";

type Extension = { foundation: string; sections: SecondYearTheorySection[]; cases?: SecondYearSportCase[]; links: { title: string; url: string }[] };
const who = { title: "OMS · Actividad física y comportamiento sedentario", url: "https://www.who.int/news-room/fact-sheets/detail/physical-activity" };
export const secondYearTheoryExtensions: Record<string, Extension> = {
  "2bach-sa1-punto-partida": {
    foundation: "La evaluación inicial es una herramienta para ganar autonomía: permite elegir prioridades y justificar un plan con evidencias. Un resultado aislado no define a una persona ni permite diagnosticar su salud. En 2º damos el paso de registrar una marca a explicar qué decisiones permite tomar y qué incertidumbre conserva.",
    sections: [{ title: "Construir y revisar un plan personal", paragraphs: ["Compara tus propias mediciones en condiciones semejantes: prueba, superficie, calentamiento, instrumento y momento del día. Anota incidencias que ayuden a interpretar diferencias. Una mejora pequeña puede depender tanto del aprendizaje de la prueba como del entrenamiento; evita atribuir cada cambio a una sola causa.", "Ejemplo educativo: quiero sostener una carrera cómoda durante más tiempo en cuatro semanas. Registro duración y esfuerzo percibido, organizo dos oportunidades semanales compatibles con mis actividades y reviso sensaciones. Primero establezco continuidad; después ajusto una variable si recupero bien. El plazo y las tareas se acuerdan con el docente según el punto de partida.", "La revisión combina resultado y proceso: ¿cumplí el plan?, ¿mantuve calidad?, ¿cómo recuperé? Si hubo interrupciones, revisa primero la viabilidad. Si cumpliste las tareas pero no hubo cambio, comprueba la medición y la relación entre estímulo y objetivo antes de aumentar la carga."], bullets: ["Punto de partida y condiciones de medida", "Una prioridad justificada", "Objetivo, indicador y plazo", "Agenda, seguimiento y reevaluación"] }], links: [who],
  },
  "2bach-sa2-condicion-fisica": {
    foundation: "Dosificar permite entrenar con una intención reconocible. El cansancio es información, pero no demuestra por sí solo que una sesión sea adecuada. En 2º relacionamos lo realizado, la respuesta personal y la recuperación para justificar progresiones que podamos revisar.",
    sections: [{ title: "Principios y microciclo: dar sentido a la semana", paragraphs: ["La especificidad relaciona tarea y objetivo; la individualización ajusta la exigencia a la persona; la continuidad sostiene el aprendizaje y la adaptación. La progresión requiere observar la respuesta, y la reversibilidad recuerda que una interrupción prolongada puede reducir adaptaciones. Estos principios actúan juntos: repetir una tarea inadecuada con regularidad no la convierte en específica.", "La frecuencia cuenta oportunidades de entrenamiento por semana. Un microciclo organiza esas sesiones junto al deporte habitual, Educación Física, estudio y descanso. Alternar exigencias y prever días suaves ayuda a sostener la calidad; no existe un intervalo de recuperación idéntico para cualquier persona y actividad.", "La supercompensación es un modelo simplificado para explicar recuperación y adaptación, no un reloj que predice el momento exacto de mejora. Duración de la fatiga, experiencia y tipo de esfuerzo cambian la respuesta. Registra RPE en una escala acordada de 0 a 10 tras la sesión: describe esfuerzo percibido, no metros ni una medición clínica.", "Comparación: 6 sprints de 20 m con pausas amplias permiten priorizar velocidad; repetir esfuerzos con pausas breves aumenta la densidad y la fatiga. La carga se describe mediante varias variables con unidades distintas: volumen, intensidad, frecuencia y densidad no se suman como una ecuación numérica."], bullets: ["Objetivo y tarea específica", "Frecuencia compatible con la agenda", "Recuperación prevista", "Una variable de progresión y un criterio de calidad"] }],
    cases: [{ sport: "Pádel", capacity: "Progresión semanal", situation: "Una pareja quiere mejorar desplazamientos laterales y llega a la última serie perdiendo control de la frenada.", proposal: "Mantener las pausas y reducir la cantidad hasta completar desplazamientos con control. Registrar repeticiones de calidad y RPE.", why: "La cantidad prevista no justifica perder la técnica; carga externa y respuesta interna aportan información diferente.", progression: "Añadir una serie en una semana posterior solo si se mantiene control y recuperación; conservar las demás variables para poder interpretar el cambio." }], links: [],
  },
  "2bach-sa3-habitos-saludables": {
    foundation: "Los hábitos hacen viable una vida activa más allá de una sesión. El objetivo educativo es reconocer relaciones entre organización, descanso, movimiento y bienestar, y elegir cambios pequeños. El seguimiento describe conductas y sensaciones sin convertirse en diagnóstico ni prescripción alimentaria.",
    sections: [{ title: "Estrés, postura y una agenda que se pueda mantener", paragraphs: ["Una semana de exámenes modifica el tiempo disponible. Distribuye el estudio con pausas breves de movimiento, reserva descanso y ajusta el entrenamiento a esa agenda. Reorganizar una semana exigente puede ser una decisión responsable, no una falta de compromiso.", "En el trabajo sentado, cambia de postura y alterna tareas cuando sea posible; no existe una postura única que debas mantener inmóvil durante horas. El bienestar también incluye disfrutar, pedir apoyo y reconocer cuándo la organización supera tus recursos.", "Antes y después de la actividad, planifica oportunidades normales de alimentación variada y acceso a agua. El propósito es llegar preparado y recuperar dentro de la rutina cotidiana, sin suplementos obligatorios ni reglas de restricción. Si hay malestar persistente, comunícalo a una persona adulta de referencia." ] }], links: [who],
  },
  "2bach-sa4-evento-deportivo": {
    foundation: "Organizar transforma una idea colectiva en una experiencia viable. El aprendizaje se demuestra al justificar decisiones y responder a incidencias, además de participar en el juego. La calidad del evento incluye seguridad, oportunidades de participación y uso responsable de recursos.",
    sections: [{ title: "Un cronograma con roles y márgenes", paragraphs: ["Para seis equipos en dos grupos de tres hacen falta tres encuentros por grupo: seis en total. Con dos pistas, tres turnos de 12 minutos de juego y 3 de transición ocupan 45 minutos. Reserva además 10 de recepción, 10 de preparación, 15 de cierre y recogida y 10 de margen: 90 minutos. Este formato garantiza dos partidos por equipo sin añadir una final que no cabe en el horario.", "Asigna coordinación, arbitraje, material, acogida, comunicación y registro de incidencias. Cada rol necesita una tarea, un momento y una persona de apoyo. La persona adulta responsable del centro supervisa seguridad y respuesta a emergencias; el alumnado debe saber a quién avisar.", "Comunica horario, acceso, reglas y opciones de participación antes del evento. Reutiliza materiales, prepara puntos de agua y organiza recogida de residuos. Evalúa participación, esperas, incidencias y opiniones; comparar esas evidencias con el propósito permite decidir qué cambiar." ] }], links: [],
  },
  "2bach-sa5-cultura-cuerpo-expresion": {
    foundation: "La expresión corporal desarrolla la capacidad de comunicar y crear con otras personas. Vincular una composición a Extremadura exige explorar una referencia y explicar cómo se transforma en movimiento. La interpretación puede ser creativa sin presentarse como reproducción histórica de una tradición.",
    sections: [{ title: "Componer, ensayar y justificar una referencia local", paragraphs: ["Elige una referencia investigable: paisaje de dehesa, un oficio, una celebración o una manifestación corporal documentada. Registra la fuente y diferencia lo observado de tu interpretación. Por ejemplo, una secuencia sobre la dehesa puede transformar apertura del espacio, recorridos curvos y cambios de ritmo en una composición propia; no constituye una danza tradicional.", "Construye una entrada, desarrollo y final. Prueba un mismo gesto con diferente intensidad, duración y nivel; después coordina unísono, canon o alternancia. Distribuye el espacio para que todos puedan intervenir y adapta movimientos a las posibilidades del grupo.", "Observa un ensayo con criterios acordados: intención legible, variedad espacial, coordinación y participación. Si se graba, sigue las indicaciones del centro sobre consentimiento y uso de imágenes. Revisa un contraste concreto y explica qué cambió en la interpretación del público." ] }], links: [],
  },
  "2bach-sa6-comunidad-activa": {
    foundation: "La autonomía también consiste en mejorar oportunidades para otras personas. Una comunidad activa necesita escuchar necesidades y probar acciones accesibles. En 2º distinguimos organizar una actividad, lograr participación y demostrar cambios: cada afirmación requiere una evidencia diferente.",
    sections: [{ title: "Del piloto al impacto: escuchar antes de ampliar", paragraphs: ["Para familias, diseña una sesión con recorridos cortos y largos, horarios consultados y opciones de movimiento sentado. Para el barrio, identifica con el centro una actividad en un espacio permitido y accesible, con responsabilidades y comunicación claras. Evita asumir que todas las familias tienen tiempo, recursos o las mismas posibilidades de desplazamiento.", "Un piloto puede registrar asistentes y personas que repiten, además de preguntar por comodidad, barreras y propuestas de cambio. Usa recuentos agregados sin publicar nombres ni datos personales. Participación e impacto no son sinónimos: una jornada concurrida no prueba un hábito duradero.", "Compara dos semanas previas con dos de prueba manteniendo horarios similares. Anota clima, exámenes u otros cambios que puedan influir. Si aumenta la participación, describe lo observado y sus límites antes de afirmar que la intervención fue la única causa. Decide con los participantes qué mantener, adaptar o retirar." ] }],
    cases: [{ sport: "Familia y barrio", capacity: "Accesibilidad", situation: "Una ruta única larga deja fuera a personas con menos tiempo o diferentes necesidades de movilidad.", proposal: "Consultar barreras, proponer dos recorridos y una alternativa en espacio accesible, con horarios y apoyo acordados con el centro.", why: "Ofrecer una actividad abierta no garantiza que todas las personas puedan participar realmente.", progression: "Probar con un grupo reducido, recoger opiniones y ajustar acceso y duración antes de convocar una actividad más amplia." }], links: [who],
  },
};
