export type SchoolExercise = { id: string; name: string; capacity: string; description: string; dose: string; recovery: string; source: string };

// Dosis escolares orientativas, adaptadas: no reproducen programas de alto rendimiento.
export const secondYearExercises: SchoolExercise[] = [
  { id: "squat", name: "Sentadilla sin carga externa", capacity: "fuerza", description: "Pies apoyados y tronco estable. Flexiona cadera y rodillas hasta un recorrido controlado y vuelve a subir. Cuádriceps y glúteos: control excéntrico al bajar y acción concéntrica al subir.", dose: "2 × 8 repeticiones · esfuerzo 4–6/10", recovery: "60–90 s entre series", source: "Jiménez, PDF pp. 143–145. Adaptación escolar sin barra." },
  { id: "lunge", name: "Zancada hacia delante", capacity: "fuerza", description: "Da un paso, desciende con control y vuelve al inicio sin perder el equilibrio. Cuádriceps, glúteos y musculatura estabilizadora. Ajusta longitud del paso y profundidad a tu control.", dose: "2 × 6 por pierna · esfuerzo 4–6/10", recovery: "60–90 s entre series", source: "Jiménez, PDF p. 151. Adaptación sin carga externa." },
  { id: "hinge", name: "Bisagra de cadera con pica", capacity: "fuerza", description: "Con rodillas ligeramente flexionadas, lleva la cadera atrás y vuelve a extenderla manteniendo el tronco estable. Aprende el patrón del peso muerto rumano; glúteos e isquiotibiales, sin hiperextender la espalda.", dose: "2 × 8 repeticiones lentas · esfuerzo 3–5/10", recovery: "60 s entre series", source: "Milo, PDF pp. 74–76. Adaptación técnica con pica." },
  { id: "calf", name: "Elevación de talones de pie", capacity: "fuerza", description: "Apoya las manos ligeramente para equilibrarte. Eleva los talones y baja sin rebotes. Trabaja gemelos y sóleo; comienza en el suelo, sin escalón ni carga adicional.", dose: "2 × 10 repeticiones · esfuerzo 4–6/10", recovery: "60 s entre series", source: "Morán, PDF p. 270. Adaptación sin polea ni escalón." },
  { id: "jump", name: "Salto vertical con recepción estable", capacity: "fuerza", description: "Flexiona suavemente cadera y rodillas, impulsa el cuerpo y aterriza amortiguando. Fuerza rápida y control excéntrico de piernas. Detén la serie si empeora la recepción.", dose: "2 × 4 saltos de calidad · sin buscar agotamiento", recovery: "15–20 s entre saltos; 2 min entre series", source: "Cappa, PDF pp. 10–13. Aplicación escolar del trabajo de fuerza rápida." },
  { id: "walkrun", name: "Alternancia de caminar y correr", capacity: "resistencia", description: "Alterna carrera suave y marcha manteniendo una respiración controlada. Regula el ritmo para completar todos los bloques de forma parecida.", dose: "4 × (2 min correr + 1 min caminar) · esfuerzo 3–5/10", recovery: "La marcha de 1 min forma parte de cada bloque", source: "Jiménez, PDF pp. 75–76. Adaptación escolar de los modos de ejercicio aeróbico." },
  { id: "continuous", name: "Carrera continua a ritmo controlado", capacity: "resistencia", description: "Corre a un ritmo regular que puedas sostener sin acelerar al principio. Participan grandes grupos musculares y el transporte y utilización de oxígeno.", dose: "10–15 min · esfuerzo 3–5/10", recovery: "2–3 min caminando al finalizar", source: "Jiménez, PDF pp. 75–76. Duración inicial adaptada al aula." },
  { id: "reaction", name: "Salida a señal y aceleración de 10 m", capacity: "velocidad", description: "Desde una posición estable, responde a la señal del profesor y acelera hacia delante. Deja espacio para frenar progresivamente. Reacción, coordinación y fuerza rápida.", dose: "4 × 10 m · rapidez con técnica estable", recovery: "90–120 s entre intentos", source: "Correr, saltar, lanzar, PDF p. 6. Distancia y dosis escolares." },
  { id: "skipping", name: "Skipping: carrera con rodillas altas", capacity: "velocidad", description: "Avanza con apoyos breves, rodillas elevadas de forma alterna y brazos coordinados. Mantén el tronco estable; busca ritmo y control antes que velocidad.", dose: "3 × 20 m · intensidad técnica moderada", recovery: "Vuelta caminando y 45–60 s", source: "Correr, saltar, lanzar, PDF pp. 6–7; rodillas altas." },
  { id: "balance", name: "Equilibrio sobre una pierna", capacity: "condicion-fisica-general", description: "Mantén el apoyo unipodal sobre suelo estable, rodilla ligeramente flexionada y mirada al frente. Usa un apoyo cercano si lo necesitas. Trabaja propiocepción y estabilización isométrica.", dose: "2 × 20 s por pierna · sin perder alineación", recovery: "30 s entre apoyos", source: "Tarantino, PDF p. 22. Aplicación escolar de apoyos sobre una pierna." },
  { id: "hipmobility", name: "Balanceo controlado de pierna", capacity: "flexibilidad-movilidad", description: "Sujétate a un apoyo estable y mueve una pierna adelante y atrás dentro de un recorrido cómodo, sin arquear el tronco. Movilidad activa de cadera y equilibrio de la pierna de apoyo.", dose: "2 × 8 movimientos por pierna · amplitud cómoda", recovery: "30 s entre series", source: "Tarantino, PDF p. 131. Adaptación de flexoextensión unipodal sin resistencia elástica." },
  { id: "stretch", name: "Estiramiento suave de gemelo en pared", capacity: "flexibilidad-movilidad", description: "Con manos en pared, adelanta una pierna y mantén el talón de la otra apoyado. Acerca el cuerpo lentamente hasta notar tensión suave en la pantorrilla, sin rebotes ni dolor.", dose: "2 × 20 s por lado · tensión suave", recovery: "20–30 s entre posiciones", source: "Adaptación didáctica: tríceps sural en Morán, PDF p. 270; control del estiramiento en Tarantino, PDF pp. 21–22." },
];
